name: Update version tags
description: Update version tags.

inputs:
  repo-token:
    description: The GITHUB_TOKEN secret.

  sha:
    description: The SHA of commit to set version tags. By default, uses the release branch or commit.

  release:
    description: The release data in a release payload/event.

runs:
  using: node16
  main: build/index.js
