name: Prepare MySQL
description: Enable MySQL, handle authentication compatibility

runs:
  using: composite
  steps:
    # Set up MySQL
    - shell: sh -e {0}
      # MySQL 8.0 uses the `caching_sha2_password` authentication method by default.
      # So here alter password with `mysql_native_password` authentication method
      # to make older PHP (7.3.x) mysql client be able to create database connections.
      run: |
        sudo systemctl start mysql.service
        mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    # Log debug information.
    - shell: sh -e {0}
      run: mysql --version
