name: GitHub Actions - Create Pull Request

on:
  push:
    branches:
      # - release/actions
      - none

jobs:
  CreateRelease:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Create a pull request for release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create( {
              ...context.repo,
              head: 'release/actions',
              base: 'main',
              title: 'Create create-release.yml',
            } );
