name: GitHub Actions - Create New Release

on:
  pull_request_review:
    types:
      - submitted

jobs:
  CreateRelease:
    name: Create GitHub actions package release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == 'release/actions' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new release
        id: new-release
        uses: actions/github-script@v6
        with:
          script: |
            const workspace = '${{ github.workspace }}';
            const packageDir = 'packages/js/github-actions';
            const { default: PackageTool } = await import( `${ workspace }/${ packageDir }/utils/package-tool.js` );

            const packageTool = new PackageTool( packageDir );
            const { version, entriesWithCategories } = packageTool.getCurrentVersionChangelog();

            const tag = `actions-v${ version }`;
            const name = `Actions ${ version }`;
            const body = `## What's Changed\n${ entriesWithCategories }`

            let release;

            try {
              const response = await github.rest.repos.createRelease( {
                ...context.repo,
                tag_name: tag,
                target_commitish: 'release/actions',
                name,
                body,
              } );
              release = response.data;
            } catch ( e ) {
              await github.rest.pulls.dismissReview( {
                ...context.repo,
                pull_number: context.payload.pull_request.number,
                review_id: context.payload.review.id,
                message: 'Release workflow failed',
              });

              throw e;
            }

            const commentBody = `New release has been created: [${ release.name }](${ release.html_url })`;
            await github.rest.issues.createComment( {
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            } );

            core.setOutput( 'release', release );

      - name: Call workflow to update version tags
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_GH_TOKEN }}
          script: |
            const release = JSON.stringify( ${{ steps.new-release.outputs.release }} );
            await github.rest.actions.createWorkflowDispatch( {
              ...context.repo,
              workflow_id: 'update-tags.yml',
              ref: 'release/actions',
              inputs: { release },
            } );
