name: Release my tools

on:
  release:
    types:
      - published
      - edited

jobs:
  CheckTagName:
    name: Check Tag Name
    runs-on: ubuntu-latest
    steps:
      - name: Check tag name
        uses: actions/github-script@v6
        with:
          script: |
            const tagReg = /^actions-v(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}$/;
            if ( ! tagReg.test( context.payload.release.tag_name ) ) {
              await github.rest.actions.cancelWorkflowRun( {
                ...context.repo,
                run_id: context.runId,
              } );
            }

  UpdateTags:
    name: Build and Update Version Tags
    runs-on: ubuntu-latest
    needs: CheckTagName
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Update version tags
        uses: woocommerce/grow/update-version-tags@actions-v1-pre
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
