name: Add Labels

on:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.head_ref, 'fix/') }}
        with:
          labels: |
            type: bug
