name: Update Tags

on:
  release:
    types:
      - published
      - edited

jobs:
  CheckTagName:
    name: Check Tag Name
    runs-on: ubuntu-latest
    outputs:
      is-matched: ${{ steps.check-tag-name.outputs.is-matched }}
    steps:
      - name: Check tag name
        id: check-tag-name
        run: |
          if [[ "${{ github.event.release.tag_name }}" =~ ^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}-actions$ ]]; then
            echo "::set-output name=is-matched::true"
          else
            echo "::set-output name=is-matched::false"
          fi

  UpdateTags:
    name: Update Tags
    runs-on: ubuntu-latest
    needs: CheckTagName
    if: needs.CheckTagName.outputs.is-matched == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Prepare node
        uses: ./github-actions/prepare-node
        with:
          node-version: 16
          cache-dependency-path: ./packages/js/github-actions
          install-deps: "no"

      - name: Commit bundle
        id: commit-bundle
        # https://api.github.com/users/github-actions%5Bbot%5D
        run: |
          cd ./packages/js/github-actions
          npm ci --ignore-scripts
          npm run build:update-version-tags
          cd -
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git rm -r .
          git checkout HEAD -- ./github-actions
          git add ./github-actions/update-version-tags/build
          git commit -m "Build the bundle of update-version-tags action."
          git push origin HEAD:refs/heads/tmp-gha-bundle
          git push -d origin tmp-gha-bundle
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Run script to update version tags
        uses: ./github-actions/update-version-tags
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.commit-bundle.outputs.sha }}
