name: Update Tags

on:
  release:
    types:
      - published
      - edited

jobs:
  UpdateTags:
    name: Update Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Prepare node
        uses: ./github-actions/prepare-node
        with:
          node-version: 16
          cache-dependency-path: ./github-actions/update-version-tags
          install-deps: "no"

      - name: Commit bundle
        id: commit-bundle
        # https://api.github.com/users/github-actions%5Bbot%5D
        run: |
          cd ./github-actions/update-version-tags
          npm ci --ignore-scripts
          npm run build
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -f ./dist/*
          git commit -m "Build the bundle of update-version-tags action."
          git push origin HEAD:refs/heads/tmp-gha-bundle
          git push -d origin tmp-gha-bundle
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Run script to update version tags
        uses: ./github-actions/update-version-tags
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.commit-bundle.outputs.sha }}
