name: Update Tags

on:
  release:
    types:
      - published
      - edited

  workflow_dispatch:
    inputs:
      release:
        description: The release data in a release payload/event.
        required: true
        type: string

jobs:
  CheckTagName:
    name: Check Tag Name
    runs-on: ubuntu-latest
    steps:
      - name: Check tag name
        uses: actions/github-script@v6
        with:
          script: |
            const { payload } = context;
            const release = payload.release || JSON.parse( payload.inputs.release );
            console.log(release.tag_name)
            const tagReg = /^actions-v(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}$/;

            if ( ! tagReg.test( release.tag_name ) ) {
              await github.rest.actions.cancelWorkflowRun( {
                ...context.repo,
                run_id: context.runId,
              } );
            }

  UpdateTags:
    name: Update Tags
    runs-on: ubuntu-latest
    needs: CheckTagName
    steps:
      - name: Checkout repository - release
        if: ${{ github.event_name == 'release' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout repository - workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ fromJSON(inputs.release).tag_name }}

      - name: Prepare node
        uses: ./github-actions/prepare-node
        with:
          node-version: 16
          cache-dependency-path: ./packages/js/github-actions
          install-deps: "no"

      # - name: Commit bundle
      #   id: commit-bundle
      #   # https://api.github.com/users/github-actions%5Bbot%5D
      #   run: |
      #     cd ./packages/js/github-actions
      #     npm ci --ignore-scripts
      #     npm run build:update-version-tags
      #     cd -
      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      #     git rm -r .
      #     git checkout HEAD -- ./github-actions
      #     git add ./github-actions/update-version-tags/build
      #     git commit -m "Build the bundle of update-version-tags action."
      #     git push origin HEAD:refs/heads/tmp-gha-bundle
      #     git push -d origin tmp-gha-bundle
      #     echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Commit bundle
        id: commit-bundle
        # https://api.github.com/users/github-actions%5Bbot%5D
        run: |
          cd ./packages/js/github-actions
          npm ci --ignore-scripts
          npm run build:update-version-tags
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Run script to update version tags
        uses: ./github-actions/update-version-tags
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.commit-bundle.outputs.sha }}
          release: ${{ inputs.release }}
